lib/workshop_feedback_web/router.ex
defmodule WorkshopFeedbackWeb.Router do
  use WorkshopFeedbackWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug WorkshopFeedback.Auth, repo: WorkshopFeedback.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", WorkshopFeedbackWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/login", SessionController, :new
    get "/logout", SessionController, :delete
    post "/login", SessionController, :create 
    resources "/feedbacks", FeedbackController
    resources "/members", MemberController
  end

  # Other scopes may use custom stacks.
  # scope "/api", WorkshopFeedbackWeb do
  #   pipe_through :api
  # end
end

lib/workshop_feedback/studentcomment/feedback.ex
defmodule WorkshopFeedback.Studentcomment.Feedback do
  use Ecto.Schema
  import Ecto.Changeset

  schema "feedbacks" do
    field :first_day_feedback, :string
    field :first_session_rating, :integer
    field :future_suggestion, :string
    field :language_preference, :string
    field :second_session_feedback, :string
    field :second_session_rating, :integer

    timestamps()
  end

  @doc false
  def changeset(feedback, attrs) do
    feedback
    |> cast(attrs, [:first_session_rating, :first_day_feedback, :second_session_rating, :second_session_feedback, :language_preference, :future_suggestion])
    |> validate_required([:first_session_rating, :first_day_feedback, :second_session_rating, :second_session_feedback, :language_preference, :future_suggestion])
  end
end

lib/workshop_feedback_web/controllers/feedback_controller.ex
defmodule WorkshopFeedbackWeb.FeedbackController do
  use WorkshopFeedbackWeb, :controller

  alias WorkshopFeedback.Studentcomment
  alias WorkshopFeedback.Studentcomment.Feedback
  plug :no_feedbacks when action in [:index]

  def index(conn, _params) do
    feedbacks = Studentcomment.list_feedbacks()
    render(conn, "index.html", feedbacks: feedbacks)
  end

  def new(conn, _params) do
    changeset = Studentcomment.change_feedback(%Feedback{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"feedback" => feedback_params}) do
    case Studentcomment.create_feedback(feedback_params) do
      {:ok, feedback} ->
        conn
        |> put_flash(:info, "Feedback created successfully.")
        |> redirect(to: Routes.feedback_path(conn, :show, feedback))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    feedback = Studentcomment.get_feedback!(id)
    render(conn, "show.html", feedback: feedback)
  end

  def edit(conn, %{"id" => id}) do
    feedback = Studentcomment.get_feedback!(id)
    changeset = Studentcomment.change_feedback(feedback)
    render(conn, "edit.html", feedback: feedback, changeset: changeset)
  end

  def update(conn, %{"id" => id, "feedback" => feedback_params}) do
    feedback = Studentcomment.get_feedback!(id)

    case Studentcomment.update_feedback(feedback, feedback_params) do
      {:ok, feedback} ->
        conn
        |> put_flash(:info, "Feedback updated successfully.")
        |> redirect(to: Routes.feedback_path(conn, :show, feedback))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", feedback: feedback, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    feedback = Studentcomment.get_feedback!(id)
    {:ok, _feedback} = Studentcomment.delete_feedback(feedback)

    conn
    |> put_flash(:info, "Feedback deleted successfully.")
    |> redirect(to: Routes.feedback_path(conn, :index))
  end
end

lib/workshop_feedback_web/views/feedback_view.ex
defmodule WorkshopFeedbackWeb.FeedbackView do
  use WorkshopFeedbackWeb, :view
end

lib/workshop_feedback_web/templates/feedback/edit.html.eex
<h1>Edit Feedback</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.feedback_path(@conn, :update, @feedback)) %>

<span><%= link "Back", to: Routes.feedback_path(@conn, :index) %></span>

lib/workshop_feedback_web/templates/feedback/form.html.eex
<% range = [1, 2, 3, 4, 5] %>


<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, "Rate the first session in a scale of 1 to 5" %>
  <%= label f, :worst_rating, 1 %> <%= radio_button f, :first_session_rating, 1 %>
  
 <%= label f, :bad_rating, 2 %> <%= radio_button f, :first_session_rating, 2 %>
  
  <%= label f, :average_rating, 3 %> <%= radio_button f, :first_session_rating, 3 %>
  
  <%= label f, :good_rating, 4 %> <%= radio_button f, :first_session_rating, 4 %>
  
   <%= label f, :excellent_rating, 5 %> <%= radio_button f, :first_session_rating, 5 %>
 
  <%= error_tag f, :first_session_rating %>

  <%= label f, "Provide your feedback on the first day's session" %>
  <%= textarea f, :first_day_feedback %>
  <%= error_tag f, :first_day_feedback %>

  <%= label f, "Rate the second session on a scale of 1 to 5" %>
  <%= label f, :worst_rating, 1 %> <%= radio_button f, :second_session_rating, 1 %>
  
 <%= label f, :bad_rating, 2 %> <%= radio_button f, :second_session_rating, 2 %>
  
  <%= label f, :average_rating, 3 %> <%= radio_button f, :second_session_rating, 3 %>
  
  <%= label f, :good_rating, 4 %> <%= radio_button f, :second_session_rating, 4 %>
  
   <%= label f, :excellent_rating, 5 %> <%= radio_button f, :second_session_rating, 5 %>
 
  <%= error_tag f, :second_session_rating %>

  <%= label f, "Provide your feedback on the second day's session" %>
  <%= textarea f, :second_session_feedback %>
  <%= error_tag f, :second_session_feedback %>

  <%= label f, "Which language would you rather prefer for the sessions to be taken" %>
  <%= label f, :english, "English" %> <%= radio_button f, :language_preference, "English" %>
  <%= label f, :tamil, "Tamil" %> <%= radio_button f, :language_preference, "Tamil" %>
  <%= error_tag f, :language_preference %>

  <%= label f, "What topic can be taken next time" %>
  <%= textarea f, :future_suggestion %>
  <%= error_tag f, :future_suggestion %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/workshop_feedback_web/templates/feedback/index.html.eex
<h1>Listing Feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>First session rating</th>
      <th>First day feedback</th>
      <th>Second session rating</th>
      <th>Second session feedback</th>
      <th>Language preference</th>
      <th>Future suggestion</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for feedback <- @feedbacks do %>
    <tr>
      <td><%= feedback.first_session_rating %></td>
      <td><%= feedback.first_day_feedback %></td>
      <td><%= feedback.second_session_rating %></td>
      <td><%= feedback.second_session_feedback %></td>
      <td><%= feedback.language_preference %></td>
      <td><%= feedback.future_suggestion %></td>

      <td>
        <span><%= link "Show", to: Routes.feedback_path(@conn, :show, feedback) %></span>
        <span><%= link "Edit", to: Routes.feedback_path(@conn, :edit, feedback) %></span>
        <span><%= link "Delete", to: Routes.feedback_path(@conn, :delete, feedback), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Feedback", to: Routes.feedback_path(@conn, :new) %></span>

lib/workshop_feedback_web/templates/feedback/new.html.eex
<%= render "form.html", Map.put(assigns, :action, Routes.feedback_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.feedback_path(@conn, :index) %></span>

lib/workshop_feedback_web/templates/feedback/show.html.eex
<h1>Show Feedback</h1>

<ul>

  <li>
    <strong>First session rating:</strong>
    <%= @feedback.first_session_rating %>
  </li>

  <li>
    <strong>First day feedback:</strong>
    <%= @feedback.first_day_feedback %>
  </li>

  <li>
    <strong>Second session rating:</strong>
    <%= @feedback.second_session_rating %>
  </li>

  <li>
    <strong>Second session feedback:</strong>
    <%= @feedback.second_session_feedback %>
  </li>

  <li>
    <strong>Language preference:</strong>
    <%= @feedback.language_preference %>
  </li>

  <li>
    <strong>Future suggestion:</strong>
    <%= @feedback.future_suggestion %>
  </li>

</ul>
<center>
  <h1>Thank you for your feedback</h1>
  <%= link "Associate with FSFTN", to: Routes.member_path(@conn, :new) %>
</center>
<span><%= link "Edit", to: Routes.feedback_path(@conn, :edit, @feedback) %></span>